// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfjbgsqlxzyifnanzmlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmamJnc3FseHp5aWZuYW56bWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5ODc2MTcsImV4cCI6MjA1MzU2MzYxN30.f_2wneU9F2p0VfuLC_3pOAAFV3lW7av3O8wdpkO1opU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);